name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.10"
          enable-cache: true

      - name: Install the dependencies
        run: make deps

      - name: Lint Check
        run: make lint-check

      - name: Formatting Check
        run: make format-check

      - name: Type Check
        run: make type-check

      - name: Run Tests
        run: make tests


